name: mmoSkillTree
version: ${releaseVersion}.${buildNumber}
description: Provides a user interface and configurable skill obtainment dependencies.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.SkillTree.MMOSkillTree
depend: [Spout, mmoCore]
